### ISSUE TITLE
Use in a browser?

### ISSUE THREAD

**Issue by NickDarvey** [microsoft/VerifiableCredentials-Crypto-SDK-Typescript#29]
Are any of the packages in this SDK suitable for use in a browser, or is has this been designed assuming node?

I was hoping to do things like [create](https://github.com/microsoft/VerifiableCredentials-Crypto-SDK-Typescript/blob/89285980a1d2280e11ff85e6110500e4a33de4bb/libs/sdk/tests/LongFormDid.spec.ts#L10-L17) a [`LongFormDid`](https://github.com/microsoft/VerifiableCredentials-Crypto-SDK-Typescript/blob/master/libs/sdk/lib/LongFormDid.ts) in a web app using a different `IKeyStore`, perhaps a `WebAuthnKeyStore` based on the [Web Authentication API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API)?

**Comment by OR13** [comment]
https://github.com/transmute-industries/sidetree.js/blob/master/packages/wallet/src/functions/toDidDocForProfile.ts#L49

https://github.com/transmute-industries/sidetree.js/blob/master/packages/wallet/src/__test__/generate-svip-operation-fixture.test.ts#L65

may help.

**Comment by NickDarvey** [comment]
It very much does, thank you @OR13
